using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Rowles.LeanCorpus.SourceGen.Models;

namespace Rowles.LeanCorpus.SourceGen.Emitters;

internal static class DocumentMapEmitter
{
    public static string Emit(DocumentModel doc)
    {
        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using global::Rowles.LeanCorpus.Document;");
        sb.AppendLine("using global::Rowles.LeanCorpus.Document.Fields;");
        sb.AppendLine("using global::Rowles.LeanCorpus.Index.Indexer;");
        sb.AppendLine("using global::Rowles.LeanCorpus.Mapping;");
        sb.AppendLine();

        bool hasNs = !string.IsNullOrEmpty(doc.Namespace);
        if (hasNs)
        {
            sb.Append("namespace ").Append(doc.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        string typeFq = doc.FullyQualifiedTypeName;
        string indexClass = doc.TypeName + "Index";
        string mapClass = doc.TypeName + "DocumentMap";

        sb.Append(doc.Accessibility).Append(" static class ").AppendLine(indexClass);
        sb.AppendLine("{");
        sb.Append("    public static LeanDocumentMap<").Append(typeFq).Append("> Map { get; } = new ").Append(mapClass).AppendLine("();");
        sb.AppendLine();

        EmitFieldsClass(sb, doc, typeFq);
        sb.AppendLine();
        EmitToDocument(sb, doc, typeFq);
        sb.AppendLine();
        EmitCreateSchema(sb, doc);
        sb.AppendLine();
        EmitFromStored(sb, doc, typeFq);

        sb.AppendLine("}");
        sb.AppendLine();

        EmitMapClass(sb, doc, typeFq, indexClass, mapClass);

        return sb.ToString();
    }

    private static void EmitFieldsClass(StringBuilder sb, DocumentModel doc, string typeFq)
    {
        sb.AppendLine("    public static class Fields");
        sb.AppendLine("    {");
        foreach (var f in doc.Fields)
        {
            string valueType = ValueTypeFor(f);
            string ft = FieldTypeFor(f);
            sb.Append("        public static readonly LeanField<").Append(typeFq).Append(", ").Append(valueType)
              .Append("> ").Append(f.PropertyName).Append(" = new(")
              .Append(StringLit(f.FieldName)).Append(", FieldType.").Append(ft).Append(", ")
              .Append(B(f.IsStored)).Append(", ").Append(B(f.IsIndexed)).Append(", ").Append(B(f.IsRequired))
              .AppendLine(");");
        }
        sb.AppendLine("    }");
    }

    private static void EmitToDocument(StringBuilder sb, DocumentModel doc, string typeFq)
    {
        sb.Append("    public static LeanDocument ToDocument(").Append(typeFq).AppendLine(" value)");
        sb.AppendLine("    {");
        if (!doc.IsValueType)
        {
            sb.AppendLine("        ArgumentNullException.ThrowIfNull(value);");
        }
        sb.AppendLine("        var doc = new LeanDocument();");
        foreach (var f in doc.Fields)
        {
            EmitToDocumentField(sb, f);
        }
        sb.AppendLine("        return doc;");
        sb.AppendLine("    }");
    }

    private static void EmitToDocumentField(StringBuilder sb, FieldModel f)
    {
        string prop = "value." + f.PropertyName;
        string name = "Fields." + f.PropertyName + ".Name";
        bool nullable = f.IsNullable;

        switch (f.FieldKind)
        {
            case FieldKind.Text:
            case FieldKind.String:
                string fieldCtor = f.FieldKind == FieldKind.Text ? "TextField" : "StringField";
                switch (f.ValueShape)
                {
                    case ValueShape.SingleValue:
                        if (nullable)
                            sb.Append("        if (").Append(prop).AppendLine(" is not null)");
                        sb.Append("            doc.Add(new ").Append(fieldCtor).Append("(").Append(name).Append(", ").Append(prop).Append(", ").Append(B(f.IsStored)).AppendLine("));");
                        break;
                    case ValueShape.StringArray:
                    case ValueShape.StringList:
                        sb.Append("        if (").Append(prop).AppendLine(" is not null)");
                        sb.AppendLine("        {");
                        sb.Append("            foreach (var s in ").Append(prop).AppendLine(")");
                        sb.AppendLine("            {");
                        sb.AppendLine("                if (s is null) continue;");
                        sb.Append("                doc.Add(new ").Append(fieldCtor).Append("(").Append(name).Append(", s, ").Append(B(f.IsStored)).AppendLine("));");
                        sb.AppendLine("            }");
                        sb.AppendLine("        }");
                        break;
                }
                break;
            case FieldKind.Numeric:
                EmitNumericProjection(sb, f, prop, name);
                break;
            case FieldKind.StoredString:
                if (f.NumericKind == NumericKind.Decimal)
                {
                    if (nullable)
                    {
                        sb.Append("        if (").Append(prop).AppendLine(" is not null)");
                        string accessor = f.IsNullable && IsValueType(f) ? prop + ".Value" : prop;
                        sb.Append("            doc.Add(new StoredField(").Append(name).Append(", LeanNumericEncoders.ToDecimalString(").Append(accessor).AppendLine(")));");
                    }
                    else
                    {
                        sb.Append("        doc.Add(new StoredField(").Append(name).Append(", LeanNumericEncoders.ToDecimalString(").Append(prop).AppendLine(")));");
                    }
                }
                else
                {
                    if (nullable)
                        sb.Append("        if (").Append(prop).AppendLine(" is not null)");
                    sb.Append("            doc.Add(new StoredField(").Append(name).Append(", ").Append(prop).AppendLine("));");
                }
                break;
            case FieldKind.StoredBinary:
                if (nullable)
                    sb.Append("        if (").Append(prop).AppendLine(" is not null)");
                sb.Append("            doc.Add(new BinaryField(").Append(name).Append(", ").Append(prop).AppendLine("));");
                break;
            case FieldKind.Vector:
                if (nullable)
                    sb.Append("        if (").Append(prop).AppendLine(" is not null)");
                sb.Append("            doc.Add(new VectorField(").Append(name).Append(", ").Append(prop).AppendLine("));");
                break;
            case FieldKind.GeoPoint:
                if (nullable)
                    sb.Append("        if (").Append(prop).AppendLine(" is not null)");
                string geoAccessor = nullable ? prop + ".Value" : prop;
                sb.Append("            doc.Add(new GeoPointField(").Append(name).Append(", ").Append(geoAccessor).Append(".Latitude, ").Append(geoAccessor).AppendLine(".Longitude));");
                break;
        }
    }

    private static void EmitNumericProjection(StringBuilder sb, FieldModel f, string prop, string name)
    {
        bool nullable = f.IsNullable;
        string accessor = nullable && IsValueType(f) ? prop + ".Value" : prop;
        string projection = f.NumericKind switch
        {
            NumericKind.Integral or NumericKind.FloatingPoint => "(double)" + accessor,
            NumericKind.DateTimeOffset => f.NumericEncoding switch
            {
                "UnixMilliseconds" => "LeanNumericEncoders.ToUnixMilliseconds(" + accessor + ")",
                "UnixSeconds" => "LeanNumericEncoders.ToUnixSeconds(" + accessor + ")",
                "UtcTicks" => "LeanNumericEncoders.ToUtcTicks(" + accessor + ")",
                _ => "(double)" + accessor + ".UtcTicks",
            },
            NumericKind.DateOnly => "LeanNumericEncoders.ToDayNumber(" + accessor + ")",
            NumericKind.TimeOnly => "LeanNumericEncoders.ToTimeOnlyTicks(" + accessor + ")",
            _ => "(double)" + accessor,
        };

        if (nullable)
        {
            sb.Append("        if (").Append(prop).AppendLine(" is not null)");
            sb.Append("            doc.Add(new NumericField(").Append(name).Append(", ").Append(projection).Append(", ").Append(B(f.IsStored)).AppendLine("));");
        }
        else
        {
            sb.Append("        doc.Add(new NumericField(").Append(name).Append(", ").Append(projection).Append(", ").Append(B(f.IsStored)).AppendLine("));");
        }
    }

    private static void EmitCreateSchema(StringBuilder sb, DocumentModel doc)
    {
        sb.AppendLine("    public static IndexSchema CreateSchema(bool strict = true)");
        sb.AppendLine("    {");
        sb.AppendLine("        var schema = new IndexSchema { StrictMode = strict };");
        foreach (var f in doc.Fields)
        {
            string ft = FieldTypeFor(f);
            sb.Append("        schema.Add(new FieldMapping(").Append(StringLit(f.FieldName)).Append(", FieldType.").Append(ft).Append(")")
              .Append(" { IsStored = ").Append(B(f.IsStored))
              .Append(", IsIndexed = ").Append(B(f.IsIndexed))
              .Append(", IsRequired = ").Append(B(f.IsRequired))
              .AppendLine(" });");
        }
        sb.AppendLine("        return schema;");
        sb.AppendLine("    }");
    }

    private static void EmitFromStored(StringBuilder sb, DocumentModel doc, string typeFq)
    {
        sb.Append("    public static ").Append(typeFq).AppendLine(" FromStoredDocument(StoredDocument document)");
        sb.AppendLine("    {");

        if (!doc.CanGenerateFromStored)
        {
            sb.Append("        throw new NotSupportedException(\"FromStoredDocument is not available for ").Append(doc.TypeName).Append(" because required member '").Append(doc.FromStoredBlockerProperty).AppendLine("' cannot be materialised from stored fields.\");");
            sb.AppendLine("    }");
            return;
        }

        // First, read values into locals
        foreach (var f in doc.Fields)
        {
            EmitFromStoredLocal(sb, f);
        }

        // Build object initialiser
        sb.Append("        return new ").Append(typeFq).AppendLine("()");
        sb.AppendLine("        {");
        for (int i = 0; i < doc.Fields.Count; i++)
        {
            var f = doc.Fields[i];
            string local = "__" + f.PropertyName;
            string assigned = AssignFromLocal(f, local);
            sb.Append("            ").Append(f.PropertyName).Append(" = ").Append(assigned);
            sb.AppendLine(i < doc.Fields.Count - 1 ? "," : "");
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static void EmitFromStoredLocal(StringBuilder sb, FieldModel f)
    {
        string local = "__" + f.PropertyName;
        string name = "Fields." + f.PropertyName + ".Name";

        switch (f.FieldKind)
        {
            case FieldKind.Text:
            case FieldKind.String:
            case FieldKind.StoredString:
                if (f.ValueShape == ValueShape.SingleValue)
                {
                    sb.Append("        var ").Append(local).Append(" = document.GetFirst(").Append(name).AppendLine(");");
                    if (f.IsRequired)
                    {
                        sb.Append("        if (").Append(local).Append(" is null) throw new InvalidOperationException(\"Missing required stored field: ").Append(f.FieldName).AppendLine("\");");
                    }
                }
                else
                {
                    sb.Append("        var ").Append(local).Append(" = document.GetValues(").Append(name).AppendLine(");");
                }
                break;
            case FieldKind.Numeric:
                sb.Append("        var ").Append(local).Append("__raw = document.GetFirst(").Append(name).AppendLine(");");
                if (f.IsRequired)
                {
                    sb.Append("        if (").Append(local).Append("__raw is null) throw new InvalidOperationException(\"Missing required stored field: ").Append(f.FieldName).AppendLine("\");");
                }
                break;
            case FieldKind.StoredBinary:
                sb.Append("        var ").Append(local).Append(" = document.GetFirstBinary(").Append(name).AppendLine(");");
                if (f.IsRequired)
                {
                    sb.Append("        if (").Append(local).Append(" is null) throw new InvalidOperationException(\"Missing required stored field: ").Append(f.FieldName).AppendLine("\");");
                }
                break;
        }
    }

    private static string AssignFromLocal(FieldModel f, string local)
    {
        switch (f.FieldKind)
        {
            case FieldKind.Text:
            case FieldKind.String:
            case FieldKind.StoredString:
                if (f.NumericKind == NumericKind.Decimal)
                {
                    // decimal-as-string: parse
                    if (f.IsRequired) return $"LeanNumericEncoders.FromDecimalString({local}!)";
                    return $"({local} is null ? default(decimal?) : LeanNumericEncoders.FromDecimalString({local}))";
                }
                if (f.ValueShape == ValueShape.SingleValue)
                {
                    return f.IsRequired ? local + "!" : local;
                }
                // collection
                if (f.PropertyTypeFullName.EndsWith("[]"))
                    return $"System.Linq.Enumerable.ToArray({local})";
                return local;
            case FieldKind.Numeric:
                return DecodeNumeric(f, local + "__raw");
            case FieldKind.StoredBinary:
                return f.IsRequired ? local + "!" : local;
            default:
                return "default!";
        }
    }

    private static string DecodeNumeric(FieldModel f, string raw)
    {
        string parse = $"double.Parse({raw}!, NumberStyles.Float, CultureInfo.InvariantCulture)";
        string fromDouble = f.NumericKind switch
        {
            NumericKind.Integral => $"checked(({UnderlyingTypeName(f)})((long){parse}))",
            NumericKind.FloatingPoint => $"({UnderlyingTypeName(f)}){parse}",
            NumericKind.DateTimeOffset => f.NumericEncoding switch
            {
                "UnixMilliseconds" => $"LeanNumericEncoders.FromUnixMilliseconds({parse})",
                "UnixSeconds" => $"LeanNumericEncoders.FromUnixSeconds({parse})",
                "UtcTicks" => $"LeanNumericEncoders.FromUtcTicks({parse})",
                _ => $"LeanNumericEncoders.FromUtcTicks({parse})",
            },
            NumericKind.DateOnly => $"LeanNumericEncoders.FromDayNumber({parse})",
            NumericKind.TimeOnly => $"LeanNumericEncoders.FromTimeOnlyTicks({parse})",
            _ => parse,
        };

        if (f.IsRequired) return fromDouble;
        // nullable: when raw is null, default
        return $"({raw} is null ? default({f.PropertyTypeFullName}) : {fromDouble})";
    }

    private static string UnderlyingTypeName(FieldModel f)
    {
        // strip nullable marker
        string t = f.PropertyTypeFullName;
        if (t.EndsWith("?")) t = t.Substring(0, t.Length - 1);
        return t;
    }

    private static void EmitMapClass(StringBuilder sb, DocumentModel doc, string typeFq, string indexClass, string mapClass)
    {
        sb.Append("file sealed class ").Append(mapClass).Append(" : LeanDocumentMap<").Append(typeFq).AppendLine(">");
        sb.AppendLine("{");
        sb.Append("    public override string DocumentName => ").Append(StringLit(doc.DocumentName)).AppendLine(";");
        sb.Append("    public override bool StrictSchema => ").Append(B(doc.StrictSchema)).AppendLine(";");
        sb.AppendLine();
        sb.Append("    public override IReadOnlyList<LeanFieldBinding<").Append(typeFq).Append(">> Fields { get; } = new LeanFieldBinding<").Append(typeFq).AppendLine(">[]");
        sb.AppendLine("    {");
        for (int i = 0; i < doc.Fields.Count; i++)
        {
            var f = doc.Fields[i];
            string ft = FieldTypeFor(f);
            sb.Append("        new LeanFieldBinding<").Append(typeFq).Append(">(")
              .Append(StringLit(f.FieldName)).Append(", FieldType.").Append(ft).Append(", ")
              .Append(B(f.IsStored)).Append(", ").Append(B(f.IsIndexed)).Append(", ").Append(B(f.IsRequired)).Append(")");
            sb.AppendLine(i < doc.Fields.Count - 1 ? "," : "");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.Append("    public override LeanDocument ToDocument(").Append(typeFq).Append(" value) => ").Append(indexClass).AppendLine(".ToDocument(value);");
        sb.Append("    public override ").Append(typeFq).Append(" FromStoredDocument(StoredDocument document) => ").Append(indexClass).AppendLine(".FromStoredDocument(document);");
        sb.Append("    public override IndexSchema CreateSchema(bool strict = true) => ").Append(indexClass).AppendLine(".CreateSchema(strict);");
        sb.AppendLine("}");
    }

    private static string FieldTypeFor(FieldModel f) => f.FieldKind switch
    {
        FieldKind.Text => "Text",
        FieldKind.String => "String",
        FieldKind.Numeric => "Numeric",
        FieldKind.Vector => "Vector",
        FieldKind.GeoPoint => "Numeric",
        FieldKind.StoredString => "Stored",
        FieldKind.StoredBinary => "Binary",
        _ => "Stored",
    };

    private static string ValueTypeFor(FieldModel f) => f.PropertyTypeFullName;

    private static bool IsValueType(FieldModel f)
    {
        switch (f.NumericKind)
        {
            case NumericKind.Integral:
            case NumericKind.FloatingPoint:
            case NumericKind.Decimal:
            case NumericKind.DateTimeOffset:
            case NumericKind.DateOnly:
            case NumericKind.TimeOnly:
                return true;
        }
        if (f.FieldKind == FieldKind.GeoPoint) return true;
        return false;
    }

    private static string B(bool b) => b ? "true" : "false";

    private static string StringLit(string s)
    {
        var sb = new StringBuilder(s.Length + 2);
        sb.Append('"');
        foreach (char c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\r': sb.Append("\\r"); break;
                case '\n': sb.Append("\\n"); break;
                case '\t': sb.Append("\\t"); break;
                case '\0': sb.Append("\\0"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
