<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\core\Rowles.Text\Rowles.Text.csproj" />
    <ProjectReference Include="..\Rowles.DataForge.Workloads\Rowles.DataForge.Workloads.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="BenchmarkDotNet.Annotations" ExcludeAssets="buildTransitive" />

    <PackageReference Include="Lucene.Net" />
    <PackageReference Include="Lucene.Net.Analysis.Common" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
