<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\Rowles.Text\Rowles.Text.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\lexicons\japanese.jlc" Link="lexicons\japanese.jlc" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
