<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="xunit" />
  </ItemGroup>

  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\Rowles.LeanCorpus\Rowles.LeanCorpus.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Rowles.LeanCorpus.Tests.Unit" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Fixtures/Indexes/*.fixture.b64" />
  </ItemGroup>

</Project>
